stages:
  - test
e2e:
  image: tmaier/docker-compose:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: test
  before_script:
    - docker-compose run codeceptjs npm install
  script:
    - docker-compose run --rm codeceptjs ./node_modules/.bin/codeceptjs run --steps
  artifacts:
    paths:
      - codeceptjs/output-error/
      - codeceptjs/snapshots/doc/
