version: '2'
services:
  client:
    image: node:8.9.4
    working_dir: /home/node
    ports:
      - '9000:9000'
    command: npm run serve:dev
    volumes:
      - ./:/home/node
    depends_on:
      - server
  server:
    image: node:8.9.4
    working_dir: /home/node
    ports:
      - '8000:8000'
    command: npm run serve:api
    volumes:
      - ./:/home/node
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongo-data:/data/db
  codeceptjs:
    image: node:8.9.4
    working_dir: /home/node
    volumes:
      - ./:/home/node
    depends_on:
      - client
      - selenium-server
  selenium-server:
    image: selenium/standalone-chrome-debug
    ports:
      - '4444:4444'
      - '5900:5900'